
dDic_regiones={
    "Arica y Parinacota":1,
    "Tarapacá":2,
    "Antofagasta":3,
    "Atacama":4,
    "Coquimbo":5,
    "Valparaíso":6,
    "Metropolitana":7,
    "O’Higgins":8,
    "Maule":9,
    "Ñuble":10,
    "Biobío":11,
    "Araucanía":12,
    "Los Ríos":13,
    "Los Lagos":14,
    "Aysén":15,
    "Magallanes":16
}

dDic_comunas = {
    'Arica' : 1,
    'Camarones' : 2,
    'General Lagos' : 3,
    'Putre' : 4,
    'Desconocido Arica y Parinacota' : 5,
    'Alto Hospicio' : 6,
    'Camina' : 7,
    'Colchane' : 8,
    'Huara' : 9,
    'Iquique' : 10,
    'Pica' : 11,
    'Pozo Almonte' : 12,
    'Desconocido Tarapaca' : 13,
    'Antofagasta' : 14,
    'Calama' : 15,
    'Maria Elena' : 16,
    'Mejillones' : 17,
    'Ollague' : 18,
    'San Pedro de Atacama' : 19,
    'Sierra Gorda' : 20,
    'Taltal' : 21,
    'Tocopilla' : 22,
    'Desconocido Antofagasta' : 23,
    'Alto del Carmen' : 24,
    'Caldera' : 25,
    'Chanaral' : 26,
    'Copiapo' : 27,
    'Diego de Almagro' : 28,
    'Freirina' : 29,
    'Huasco' : 30,
    'Tierra Amarilla' : 31,
    'Vallenar' : 32,
    'Desconocido Atacama' : 33,
    'Andacollo' : 34,
    'Canela' : 35,
    'Combarbala' : 36,
    'Coquimbo' : 37,
    'Illapel' : 38,
    'La Higuera' : 39,
    'La Serena' : 40,
    'Los Vilos' : 41,
    'Monte Patria' : 42,
    'Ovalle' : 43,
    'Paiguano' : 44,
    'Punitaqui' : 45,
    'Rio Hurtado' : 46,
    'Salamanca' : 47,
    'Vicuna' : 48,
    'Desconocido Coquimbo' : 49,
    'Algarrobo' : 50,
    'Cabildo' : 51,
    'Calera' : 52,
    'Calle Larga' : 53,
    'Cartagena' : 54,
    'Casablanca' : 55,
    'Catemu' : 56,
    'Concon' : 57,
    'El Quisco' : 58,
    'El Tabo' : 59,
    'Hijuelas' : 60,
    'Isla de Pascua' : 61,
    'Juan Fernandez' : 62,
    'La Cruz' : 63,
    'La Ligua' : 64,
    'Limache' : 65,
    'Llaillay' : 66,
    'Los Andes' : 67,
    'Nogales' : 68,
    'Olmue' : 69,
    'Panquehue' : 70,
    'Papudo' : 71,
    'Petorca' : 72,
    'Puchuncavi' : 73,
    'Putaendo' : 74,
    'Quillota' : 75,
    'Quilpue' : 76,
    'Quintero' : 77,
    'Rinconada' : 78,
    'San Antonio' : 79,
    'San Esteban' : 80,
    'San Felipe' : 81,
    'Santa Maria' : 82,
    'Santo Domingo' : 83,
    'Valparaiso' : 84,
    'Villa Alemana' : 85,
    'Vina del Mar' : 86,
    'Zapallar' : 87,
    'Desconocido Valparaiso' : 88,
    'Alhue' : 89,
    'Buin' : 90,
    'Calera de Tango' : 91,
    'Cerrillos' : 92,
    'Cerro Navia' : 93,
    'Colina' : 94,
    'Conchali' : 95,
    'Curacavi' : 96,
    'El Bosque' : 97,
    'El Monte' : 98,
    'Estacion Central' : 99,
    'Huechuraba' : 100,
    'Independencia' : 101,
    'Isla de Maipo' : 102,
    'La Cisterna' : 103,
    'La Florida' : 104,
    'La Granja' : 105,
    'La Pintana' : 106,
    'La Reina' : 107,
    'Lampa' : 108,
    'Las Condes' : 109,
    'Lo Barnechea' : 110,
    'Lo Espejo' : 111,
    'Lo Prado' : 112,
    'Macul' : 113,
    'Maipu' : 114,
    'Maria Pinto' : 115,
    'Melipilla' : 116,
    'Nunoa' : 117,
    'Padre Hurtado' : 118,
    'Paine' : 119,
    'Pedro Aguirre Cerda' : 120,
    'Penaflor' : 121,
    'Penalolen' : 122,
    'Pirque' : 123,
    'Providencia' : 124,
    'Pudahuel' : 125,
    'Puente Alto' : 126,
    'Quilicura' : 127,
    'Quinta Normal' : 128,
    'Recoleta' : 129,
    'Renca' : 130,
    'San Bernardo' : 131,
    'San Joaquin' : 132,
    'San Jose de Maipo' : 133,
    'San Miguel' : 134,
    'San Pedro' : 135,
    'San Ramon' : 136,
    'Santiago' : 137,
    'Talagante' : 138,
    'Tiltil' : 139,
    'Vitacura' : 140,
    'Desconocido Metropolitana' : 141,
    'Chepica' : 142,
    'Chimbarongo' : 143,
    'Codegua' : 144,
    'Coinco' : 145,
    'Coltauco' : 146,
    'Donihue' : 147,
    'Graneros' : 148,
    'La Estrella' : 149,
    'Las Cabras' : 150,
    'Litueche' : 151,
    'Lolol' : 152,
    'Machali' : 153,
    'Malloa' : 154,
    'Marchihue' : 155,
    'Mostazal' : 156,
    'Nancagua' : 157,
    'Navidad' : 158,
    'Olivar' : 159,
    'Palmilla' : 160,
    'Paredones' : 161,
    'Parelillo' : 162,
    'Peumo' : 163,
    'Pichidegua' : 164,
    'Pichilemu' : 165,
    'Placilla' : 166,
    'Pumanque' : 167,
    'Quinta de Tilcoco' : 168,
    'Rancagua' : 169,
    'Rengo' : 170,
    'Requinoa' : 171,
    'San Fernando' : 172,
    'San Vicente' : 173,
    'Santa Cruz' : 174,
    'Desconocido O’Higgins' : 175,
    'Cauquenes' : 176,
    'Chanco' : 177,
    'Colbun' : 178,
    'Constitucion' : 179,
    'Curepto' : 180,
    'Curico' : 181,
    'Empedrado' : 182,
    'Hualane' : 183,
    'Licanten' : 184,
    'Linares' : 185,
    'Longavi' : 186,
    'Maule' : 187,
    'Molina' : 188,
    'Parral' : 189,
    'Pelarco' : 190,
    'Pelluhue' : 191,
    'Pencahue' : 192,
    'Rauco' : 193,
    'Retiro' : 194,
    'Rio Claro' : 195,
    'Romeral' : 196,
    'Sagrada Familia' : 197,
    'San Clemente' : 198,
    'San Javier' : 199,
    'San Rafael' : 200,
    'Talca' : 201,
    'Teno' : 202,
    'Vichuquen' : 203,
    'Villa Alegre' : 204,
    'Yerbas Buenas' : 205,
    'Desconocido Maule' : 206,
    'Bulnes' : 207,
    'Chillan' : 208,
    'Chillan Viejo' : 209,
    'Cobquecura' : 210,
    'Coelemu' : 211,
    'Coihueco' : 212,
    'El Carmen' : 213,
    'Ninhue' : 214,
    'Niquen' : 215,
    'Pemuco' : 216,
    'Pinto' : 217,
    'Portezuelo' : 218,
    'Quillon' : 219,
    'Quirihue' : 220,
    'Ranquil' : 221,
    'San Carlos' : 222,
    'San Fabian' : 223,
    'San Ignacio' : 224,
    'San Nicolas' : 225,
    'Treguaco' : 226,
    'Yungay' : 227,
    'Desconocido Nuble' : 228,
    'Alto Biobio' : 229,
    'Antuco' : 230,
    'Arauco' : 231,
    'Cabrero' : 232,
    'Canete' : 233,
    'Chiguayante' : 234,
    'Concepcion' : 235,
    'Contulmo' : 236,
    'Coronel' : 237,
    'Curanilahue' : 238,
    'Florida' : 239,
    'Hualpen' : 240,
    'Hualqui' : 241,
    'Laja' : 242,
    'Lebu' : 243,
    'Los Alamo' : 244,
    'Los Angeles' : 245,
    'Lota' : 246,
    'Mulchen' : 247,
    'Nacimiento' : 248,
    'Negrete' : 249,
    'Penco' : 250,
    'Quilaco' : 251,
    'Quilleco' : 252,
    'San Pedro de la Paz' : 253,
    'San Rosendo' : 254,
    'Santa Barbara' : 255,
    'Santa Juana' : 256,
    'Talcahuano' : 257,
    'Tirua' : 258,
    'Tome' : 259,
    'Tucapel' : 260,
    'Yumbel' : 261,
    'Desconocido Biobio' : 262,
    'Angol' : 263,
    'Carahue' : 264,
    'Cholchol' : 265,
    'Collipulli' : 266,
    'Cunco' : 267,
    'Curacautin' : 268,
    'Curarrehue' : 269,
    'Ercilla' : 270,
    'Freire' : 271,
    'Galvarino' : 272,
    'Gorbea' : 273,
    'Lautaro' : 274,
    'Loncoche' : 275,
    'Lonquimay' : 276,
    'Los Sauces' : 277,
    'Lumaco' : 278,
    'Melipeuco' : 279,
    'Nueva Imperial' : 280,
    'Padre Las Casas' : 281,
    'Perquenco' : 282,
    'Pitrufquen' : 283,
    'Pucon' : 284,
    'Puren' : 285,
    'Renaico' : 286,
    'Saavedra' : 287,
    'Temuco' : 288,
    'Teodoro Schmidt' : 289,
    'Tolten' : 290,
    'Traiguen' : 291,
    'Victoria' : 292,
    'Vilcun' : 293,
    'Villarrica' : 294,
    'Desconocido Araucania' : 295,
    'Corral' : 296,
    'Futrono' : 297,
    'La Union' : 298,
    'Lago Ranco' : 299,
    'Lanco' : 300,
    'Los Lagos' : 301,
    'Mafil' : 302,
    'Mariquina' : 303,
    'Paillaco' : 304,
    'Panguipulli' : 305,
    'Rio Bueno' : 306,
    'Valdivia' : 307,
    'Desconocido Los Rios' : 308,
    'Ancud' : 309,
    'Calbuco' : 310,
    'Castro' : 311,
    'Chaiten' : 312,
    'Chonchi' : 313,
    'Cochamo' : 314,
    'Curaco de Velez' : 315,
    'Fresia' : 316,
    'Frutillar' : 317,
    'Futaleufu' : 318,
    'Hualaihue' : 319,
    'Llanquihue' : 320,
    'Los Muermos' : 321,
    'Maullin' : 322,
    'Osorno' : 323,
    'Palena' : 324,
    'Puerto Montt' : 325,
    'Puerto Octay' : 326,
    'Puerto Varas' : 327,
    'Puqueldon' : 328,
    'Purranque' : 329,
    'Puyehue' : 330,
    'Queilen' : 331,
    'Quellon' : 332,
    'Quemchi' : 333,
    'Quinchao' : 334,
    'Rio Negro' : 335,
    'San Juan de la Costa' : 336,
    'San Pablo' : 337,
    'Desconocido Los Lagos' : 338,
    'Aysen' : 339,
    'Chile Chico' : 340,
    'Cisnes' : 341,
    'Cochrane' : 342,
    'Coyhaique' : 343,
    'Guaitecas' : 344,
    'Lago Verde' : 345,
    'OHiggins' : 346,
    'Rio Ibanez' : 347,
    'Tortel' : 348,
    'Desconocido Aysen' : 349,
    'Antartica' : 350,
    'Cabo de Hornos' : 351,
    'Laguna Blanca' : 352,
    'Natales' : 353,
    'Porvenir' : 354,
    'Primavera' : 355,
    'Punta Arenas' : 356,
    'Rio Verde' : 357,
    'San Gregorio' : 358,
    'Timaukel' : 359,
    'Torres del Paine' : 360,
    'Desconocido Magallanes' : 361
}

aRegiones=["Arica y Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Metropolitana",
    "O’Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén",
    "Magallanes"]

aComArica = ["Arica",
    "Camarones",
    "General Lagos",
    "Putre",
    "Desconocido Arica y Parinacota"]

aComTarapaca=["Alto Hospicio",
    "Camina",
    "Colchane",
    "Huara","Iquique",
    "Pica",
    "Pozo Almonte",
    "Desconocido Tarapaca"]

aComAntofagasta = ["Antofagasta",
    "Calama",
    "Maria Elena",
    "Mejillones",
    "Ollague",
    "San Pedro de Atacama",
    "Sierra Gorda",
    "Taltal",
    "Tocopilla",
    "Desconocido Antofagasta"]

aComAtacama = ["Alto del Carmen",
    "Caldera",
    "Chanaral",
    "Copiapo",
    "Diego de Almagro",
    "Freirina",
    "Huasco",
    "Tierra Amarilla",
    "Vallenar",
    "Desconocido Atacama"]

aComCoquimbo = ["Andacollo",
    "Canela",
    "Combarbala",
    "Coquimbo",
    "Illapel",
    "La Higuera",
    "La Serena",
    "Los Vilos",
    "Monte Patria",
    "Ovalle",
    "Paiguano",
    "Punitaqui",
    "Rio Hurtado",
    "Salamanca",
    "Vicuna",
    "Desconocido Coquimbo"]

aComValparaiso = ["Algarrobo",
    "Cabildo",
    "Calera",
    "Calle Larga",
    "Cartagena",
    "Casablanca",
    "Catemu",
    "Concon",
    "El Quisco",
    "El Tabo",
    "Hijuelas",
    "Isla de Pascua",
    "Juan Fernandez",
    "La Cruz",
    "La Ligua",
    "Limache",
    "Llaillay",
    "Los Andes",
    "Nogales",
    "Olmue",
    "Panquehue",
    "Papudo",
    "Petorca",
    "Puchuncavi",
    "Putaendo",
    "Quillota",
    "Quilpue",
    "Quintero",
    "Rinconada",
    "San Antonio",
    "San Esteban",
    "San Felipe",
    "Santa Maria",
    "Santo Domingo",
    "Valparaiso",
    "Villa Alemana",
    "Vina del Mar",
    "Zapallar",
    "Desconocido Valparaiso"]

aComMetropolitana = ["Alhue",
    "Buin",
    "Calera de Tango",
    "Cerrillos",
    "Cerro Navia",
    "Colina",
    "Conchali",
    "Curacavi",
    "El Bosque",
    "El Monte",
    "Estacion Central",
    "Huechuraba",
    "Independencia",
    "Isla de Maipo",
    "La Cisterna",
    "La Florida",
    "La Granja",
    "La Pintana",
    "La Reina",
    "Lampa",
    "Las Condes",
    "Lo Barnechea",
    "Lo Espejo",
    "Lo Prado",
    "Macul",
    "Maipu",
    "Maria Pinto",
    "Melipilla",
    "Nunoa",
    "Padre Hurtado",
    "Paine",
    "Pedro Aguirre Cerda",
    "Penaflor",
    "Penalolen",
    "Pirque",
    "Providencia",
    "Pudahuel",
    "Puente Alto",
    "Quilicura",
    "Quinta Normal",
    "Recoleta",
    "Renca",
    "San Bernardo",
    "San Joaquin",
    "San Jose de Maipo",
    "San Miguel",
    "San Pedro",
    "San Ramon",
    "Santiago",
    "Talagante",
    "Tiltil",
    "Vitacura",
    "Desconocido Metropolitana"]

aComOhiggins = ["Chepica",
    "Chimbarongo",
    "Codegua",
    "Coinco",
    "Coltauco",
    "Donihue",
    "Graneros",
    "La Estrella",
    "Las Cabras",
    "Litueche",
    "Lolol",
    "Machali",
    "Malloa",
    "Marchihue",
    "Mostazal",
    "Nancagua",
    "Navidad",
    "Olivar",
    "Palmilla",
    "Paredones",
    "Parelillo",
    "Peumo",
    "Pichidegua",
    "Pichilemu",
    "Placilla",
    "Pumanque",
    "Quinta de Tilcoco",
    "Rancagua",
    "Rengo",
    "Requinoa",
    "San Fernando",
    "San Vicente",
    "Santa Cruz",
    "Desconocido O’Higgins"]

aComMaule = ["Cauquenes",
    "Chanco",
    "Colbun",
    "Constitucion",
    "Curepto",
    "Curico",
    "Empedrado",
    "Hualane",
    "Licanten",
    "Linares",
    "Longavi",
    "Maule",
    "Molina",
    "Parral",
    "Pelarco",
    "Pelluhue",
    "Pencahue",
    "Rauco",
    "Retiro",
    "Rio Claro",
    "Romeral",
    "Sagrada Familia",
    "San Clemente",
    "San Javier",
    "San Rafael",
    "Talca",
    "Teno",
    "Vichuquen",
    "Villa Alegre",
    "Yerbas Buenas",
    "Desconocido Maule"]

aComNuble = ["Bulnes",
    "Chillan", 
    "Chillan Viejo",
    "Cobquecura",
    "Coelemu",
    "Coihueco",
    "El Carmen",
    "Ninhue",
    "Niquen",
    "Pemuco",
    "Pinto",
    "Portezuelo",
    "Quillon",
    "Quirihue",
    "Ranquil",
    "San Carlos",
    "San Fabian",
    "San Ignacio",
    "San Nicolas",
    "Treguaco",
    "Yungay",
    "Desconocido Nuble"]

aComBiobio = ["Alto Biobio",
    "Antuco",
    "Arauco",
    "Cabrero",
    "Canete",
    "Chiguayante",
    "Concepcion",
    "Contulmo",
    "Coronel",
    "Curanilahue",
    "Florida",
    "Hualpen",
    "Hualqui",
    "Laja",
    "Lebu",
    "Los Alamo",
    "Los Angeles",
    "Lota",
    "Mulchen",
    "Nacimiento",
    "Negrete",
    "Penco",
    "Quilaco",
    "Quilleco",
    "San Pedro de la Paz",
    "San Rosendo",
    "Santa Barbara",
    "Santa Juana",
    "Talcahuano",
    "Tirua",
    "Tome",
    "Tucapel",
    "Yumbel",
    "Desconocido Biobio"]

aComAraucania =["Angol",
    "Carahue",
    "Cholchol",
    "Collipulli",
    "Cunco",
    "Curacautin",
    "Curarrehue",
    "Ercilla",
    "Freire",
    "Galvarino",
    "Gorbea",
    "Lautaro",
    "Loncoche",
    "Lonquimay",
    "Los Sauces",
    "Lumaco",
    "Melipeuco",
    "Nueva Imperial",
    "Padre Las Casas",
    "Perquenco",
    "Pitrufquen",
    "Pucon",
    "Puren",
    "Renaico",
    "Saavedra",
    "Temuco",
    "Teodoro Schmidt",
    "Tolten",
    "Traiguen",
    "Victoria",
    "Vilcun",
    "Villarrica",
    "Desconocido Araucania"]

aComRios = ["Corral",
    "Futrono",
    "La Union",
    "Lago Ranco",
    "Lanco",
    "Los Lagos",
    "Mafil",
    "Mariquina",
    "Paillaco",
    "Panguipulli",
    "Rio Bueno",
    "Valdivia",
    "Desconocido Los Rios"]

aComLagos = ["Ancud",
    "Calbuco",
    "Castro",
    "Chaiten",
    "Chonchi",
    "Cochamo",
    "Curaco de Velez",
    "Fresia",
    "Frutillar",
    "Futaleufu",
    "Hualaihue",
    "Llanquihue",
    "Los Muermos",
    "Maullin",
    "Osorno",
    "Palena",
    "Puerto Montt",
    "Puerto Octay",
    "Puerto Varas",
    "Puqueldon",
    "Purranque",
    "Puyehue",
    "Queilen",
    "Quellon",
    "Quemchi",
    "Quinchao",
    "Rio Negro",
    "San Juan de la Costa",
    "San Pablo",
    "Desconocido Los Lagos"]

aComAysen = ["Aysen",
    "Chile Chico",
    "Cisnes",
    "Cochrane",
    "Coyhaique",
    "Guaitecas",
    "Lago Verde",
    "OHiggins",
    "Rio Ibanez",
    "Tortel",
    "Desconocido Aysen"]

aComMagallanes = ["Antartica",
    "Cabo de Hornos",
    "Laguna Blanca",
    "Natales",
    "Porvenir",
    "Primavera",
    "Punta Arenas",
    "Rio Verde",
    "San Gregorio",
    "Timaukel",
    "Torres del Paine",
    "Desconocido Magallanes"]

dDic_rango={
    "<=39":1,
    "40-49":2,
    "50-59":3,
    "60-69":4,
    "70-79":5,
    "80-89":6,
    ">=90":7
}
aRango=["<=39",
    "40-49",
    "50-59",
    "60-69",
    "70-79",
    "80-89",
    ">=90"
]